# Reference: https://docs.codeclimate.com/docs/advanced-configuration#section-checks
# Reference of plugins: https://docs.codeclimate.com/docs/list-of-engines

version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  rubocop:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.rb"
exclude_paths:
- script/
- spec/
