# Travis build cycle: https://docs.travis-ci.com/user/job-lifecycle
# Codeclimate setup: https://docs.codeclimate.com/docs/travis-ci-test-coverage

env:
  global:
    - CC_TEST_REPORTER_ID=9a84a9f695de3b120b6fcead4e089b45420f7518fb2123dc5424f862d381c4ff
language: ruby
rvm:
  - 3.0.1
cache: bundler
before_install: gem install bundler -v 2.2.18
#install: bundle install # Default
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
#script: bundle exec rake # Default
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
