# frozen_string_literal: true

require_relative "google_search_console_verification_file/version"
require_relative "google_search_console_verification_file/verification_file_generator"
#require "jekyll-google_search_console_verification_file/verification_file_generator"

module Jekyll
  module GoogleSearchConsoleVerificationFile
  end
end
